version: '3.8'
services:
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: optic_chat_development

  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 5000 -b '0.0.0.0'"
    volumes:
      - .:/optic_chat
      - init_volume:/opt/app-initialized
    ports:
      - "5000:5000"
    environment:
      RAILS_ENV: development
      DATABASE_URL: postgres://user:password@db/optic_chat_development
    depends_on:
      - db
      - redis
  
  tests:
    build: .
    environment:
      RAILS_ENV: test
      DATABASE_URL: postgres://user:password@db/optic_chat_test
    command: /usr/bin/entrypoint.sh tests
    volumes:
      - .:/optic_chat
      - init_volume:/opt/app-initialized
    depends_on:
      - db
      - redis

  redis:
    image: redis:alpine
    ports:
      - "6380:6379"

volumes:
  postgres_data:
  init_volume:
  
# version: '3.8'
# services:
#   db:
#     image: postgres
#     volumes:
#       - postgres_data_dev:/var/lib/postgresql/data
#     environment:
#       POSTGRES_PASSWORD: password
#       POSTGRES_USER: user
#       POSTGRES_DB: optic_chat_development

#   db_test:
#     image: postgres
#     volumes:
#       - postgres_data_test:/var/lib/postgresql/data
#     environment:
#       POSTGRES_PASSWORD: password
#       POSTGRES_USER: user
#       POSTGRES_DB: optic_chat_test

#   web:
#     build: .
#     command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 5000 -b '0.0.0.0'"
#     volumes:
#       - .:/optic_chat
#       - init_volume:/opt/app-initialized
#     ports:
#       - "5000:5000"
#     environment:
#       RAILS_ENV: development
#       DATABASE_URL: postgres://user:password@db/optic_chat_development
#     depends_on:
#       - db
#       - redis
  
#   tests:
#     build: .
#     environment:
#       RAILS_ENV: test
#       DATABASE_URL: postgres://user:password@db_test:5432/optic_chat_test
#     command: /usr/bin/entrypoint.sh tests
#     volumes:
#       - .:/optic_chat
#       - init_volume:/opt/app-initialized
#     depends_on:
#       - db_test
#       - redis

#   redis:
#     image: redis:alpine
#     ports:
#       - "6380:6379"

# volumes:
#   postgres_data_dev:
#   postgres_data_test:
#   init_volume:
