default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: user
  password: password
  host: db

development:
  <<: *default
  database: optic_chat_development

test:
  <<: *default
  database: optic_chat_test

production:
  <<: *default
  database: optic_chat_production
  username: optic_chat
  password: <%= ENV["OPTIC_CHAT_DATABASE_PASSWORD"] %>
